### ISSUE TITLE
Weird Output on Nexus 4 5.1.1

### ISSUE THREAD

**Issue by lolobosse** [PGSSoft/scrollscreenshot#5]
Hi there,

I found the idea of this tool great but I've difficulties to make it work:

I receive something like this as result: 

![out](https://cloud.githubusercontent.com/assets/5024077/8376219/ea65126e-1c04-11e5-8b92-3ab349d6138e.png)

and I cannot figure out why... :cry: 

Does someone have an idea?

Command was: 
`java -cp scrollscreenshot-latest.jar com.pgssoft.scrollscreenshot.ScrollScreenShot -i 2 --pathsdk ~/Android_Dev/android-sdk-macosx/ -c 5`

Can it be because I have Android Studio opened and a debugger active ?
Best

**Comment by tomekziel** [comment]
Please try option:
     -e, --inertia
       Inertia of content, how many pixels are required to start dragging. Use
       non-zero value if there are duplicated stripes.
       Default: 0

Is there any delay if you scroll page by hand?

**Comment by lolobosse** [comment]
Yes there is delay, I'll try it out. 

BTW works perfectly on S5

It could be better with -e (I try many values out) but I find no satisfying value, is there a way to calculate what could be the best value?

Best

**Comment by lolobosse** [comment]
That's my best:

![out](https://cloud.githubusercontent.com/assets/5024077/8376368/d9c9bcd2-1c06-11e5-9cfc-4bdc29a949a4.png) with `-e = 375`

**Comment by tomekziel** [comment]
Try "-c 2 -s separate" to get individual files and compare Y pixel offset by hand between two files.

**Comment by lolobosse** [comment]
I got a `java.lang.NullPointerException` with the `-s` option... Can you reproduce it as well ?

**Comment by lolobosse** [comment]
I'll try again this evening and use the s5 yet because I'm working and I need to speed up, I come to you back this evening :smile: What's your timezone ?

**Comment by rfrosetta** [comment]
I am getting similar results on a Galaxy S6 Edge.  -e either has no effect, or makes the striping worse. -s gives an NPE as stated by @lolobosse

**Comment by ryancford** [comment]
I am getting similar results on a Galaxy S6 Edge. -e either has no effect, or makes the striping worse. -s gives an NPE as stated by @lolobosse

**Comment by tomekziel** [comment]
Please use `-s` option with version 0.3, which fixes the `NullPointerException`. Feel free to open another ticket, if there will be any other issues

**Comment by lolobosse** [comment]
:+1:

**Comment by ryancford** [comment]
The crash is fixed, however I still get the striping.  I have compared the images produced by -c 2 -s separate to get the Y offset, and it seems to make things worse.  Any other suggestions?

**Comment by tomekziel** [comment]
@ryancford please open new ticket with your output images attached (with and without -c switch)
